// =========================================
// 曲目リストデータ（songList.js）
// =========================================

const songList = [
    { name: "I wish", kana: "アイウィッシュ" },
    { name: "identity my ultimatum", kana: "アイデンティティマイアルティメイタム", subInfo: "Sho from MY FIRST STORY feat.駒形友梨/ウエノルカ(眩暈SIREN)" },
    { name: "アクアリウム", kana: "アクアリウム" },
    { name: "a Day~and the light comes~", kana: "アデイアンドザライトカムズ" },
    { name: "our story", kana: "アワーストーリー" },
    { name: "Yellow Love", kana: "イエローラブ" },
    { name: "It's HEAVEN", kana: "イッツヘブン" },
    { name: "invincible self", kana: "インヴィンシブルセルフ" },
    { name: "insomnia", kana: "インソムニア" },
    { name: "Welcome!!", kana: "ウェルカム", subInfo: "765 MILLION ALLSTARS" },
    { name: "empty", kana: "エンプティ" },
    { name: "August 31", kana: "オーガストサーティファースト" },
    { name: "オービタル", kana: "オービタル" },
    { name: "All for one Forever", kana: "オールフォーワンフォーエバー", subInfo: "映画プリキュアオールスターズF" },
    { name: "おそろい", kana: "オソロイ" },
    { name: "On My Way", kana: "オンマイウェイ" },
    { name: "カラフルVacation", kana: "カラフルバケーション", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "創だらけの詩", kana: "キズダラケノウタ" },
    { name: "キミと恋の予感", kana: "キミトコイノヨカン" },
    { name: "君の心に触れる歌", kana: "キミノココロニフレルウタ" },
    { name: "今日は", kana: "キョウハ" },
    { name: "キラキラ⭐︎スイート⭐︎マドモアゼル", kana: "キラキラスイートマドモアゼル", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "グッドサイン", kana: "グッドサイン", subInfo: "765 MILLION ALLSTARS" },
    { name: "Good Night", kana: "グッドナイト" },
    { name: "Glow Map", kana: "グロウマップ", subInfo: "765 MILLION ALLSTARS" },
    { name: "クロックワイズ", kana: "クロックワイズ" },
    { name: "Crossing!", kana: "クロッシング", subInfo: "765 MILLION ALLSTARS" },
    { name: "クロワッサン", kana: "クロワッサン" },
    { name: "孤悲", kana: "コイ" },
    { name: "going forward", kana: "ゴーイングフォーワード" },
    { name: "call me today", kana: "コールミートゥデイ" },
    { name: "コンパス", kana: "コンパス" },
    { name: "Thank You!", kana: "サンキュー", subInfo: "765 MILLION ALLSTARS" },
    { name: "SHINE!! キラキラ⭐︎プリキュアアラモード", kana: "シャインキラキラプリキュアアラモード", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "Champagne Gold", kana: "シャンパンゴールド", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "シングデイズ", kana: "シングデイズ" },
    { name: "真珠星", kana: "シンジュボシ" },
    { name: "starting in the haze", kana: "スターティングインザヘイズ" },
    { name: "SPARKERS", kana: "スパーカーズ", subInfo: "高山紗代子" },
    { name: "7Days A Week!!", kana: "セブンデイズアウィーク", subInfo: "765 MILLION ALLSTARS" },
    { name: "ソノヒ", kana: "ソノヒ" },
    { name: "蝶々むすび", kana: "チョウチョムスビ", subInfo: "765 MILLION ALLSTARS" },
    { name: "2 world", kana: "ツーワールド" },
    { name: "Talk 2 Night", kana: "トークトゥナイト" },
    { name: "時の葉", kana: "トキノハ" },
    { name: "トマレのススメ", kana: "トマレノススメ" },
    { name: "Dreaming!", kana: "ドリーミング", subInfo: "765 MILLION ALLSTARS" },
    { name: "Dreaming Night", kana: "ドリーミングナイト" },
    { name: "Night Walk", kana: "ナイトウォーク" },
    { name: "night sea", kana: "ナイトシー" },
    { name: "Neon Sign", kana: "ネオンサイン" },
    { name: "NExt Wave!!", kana: "ネクストウェーブ", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "Harmony 4 You", kana: "ハーモニーフォーユー", subInfo: "765 MILLION ALLSTARS" },
    { name: "ばいばい", kana: "バイバイ" },
    { name: "はじめからきっと", kana: "ハジメカラキット" },
    { name: "happy weekend", kana: "ハッピーウィークエンド" },
    { name: "Here I Am", kana: "ヒアアイアム" },
    { name: "ビターフラッペ", kana: "ビターフラッペ" },
    { name: "First Step", kana: "ファーストステップ" },
    { name: "FLY!", kana: "フライ" },
    { name: "Flyers!!!", kana: "フライヤーズ", subInfo: "765 MILLION ALLSTARS" },
    { name: "Brand New Theater!", kana: "ブランニューシアター", subInfo: "765 MILLION ALLSTARS" },
    { name: "メイズ", kana: "メイズ" },
    { name: "優しい雨", kana: "ヤサシイアメ" },
    { name: "勇気が君を待ってる", kana: "ユウキガキミヲマッテル", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "UNION!!", kana: "ユニオン", subInfo: "765 MILLION ALLSTARS" },
    { name: "夢にかけるRainbow", kana: "ユメニカケルレインボー", subInfo: "765 MILLION ALLSTARS" },
    { name: "Rat A Tat!!!", kana: "ラタタ", subInfo: "765 MILLION ALLSTARS" },
    { name: "Love is Action!", kana: "ラブイズアクション" },
    { name: "ララルハレルヤ", kana: "ララルハレルヤ" },
    { name: "リコリス", kana: "リコリス", subInfo: "東堂凛（OVER RUN!!）" },
    { name: "Lu La La⭐︎Lumière", kana: "ルララルミエール", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "Lonely Blue が終わる頃には", kana: "ロンリーブルーガオワルコロニハ" },
    { name: "Many Many Musik", kana: "メニメニムジーク" },
    { name: "トレビアンサンブル!!", kana: "トレビアンサンブル", subInfo: "映画キラキラ☆プリキュアアラモード パリッと!想い出のミルフィーユ!" },
    { name: "We are the future！", kana: "ウィーアーザフューチャー" },
    /*
    //===========================    
    //BURNOUT SYNDROMES
    //===========================
    { name: "100万回のアイ・ラヴ・ユー", kana: "ヒャクマカイノアイラブユー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "2020年渋谷の旅", kana: "ニセンニジュウネンシブヤノタビ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Amateras", kana: "アマテラス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BABEL", kana: "バベル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BLIZZARD", kana: "ブリザード", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Bottle Ship Boys", kana: "ボトルシップボーイズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BREAK DANCER", kana: "ブレイクダンサー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Dragonfly", kana: "ドラゴンフライ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Dream On!!", kana: "ドリームオン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "FLY HIGH!!", kana: "フライハイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "FORÇA", kana: "フォルサ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Good Morning [New] World!", kana: "グッドモーニングニューワールド", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Good Morning World!", kana: "グッドモーニングワールド", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Hikousen", kana: "ヒコウセン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "i am a HERO", kana: "アイアムアヒーロー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "I Don’t Wanna Die in the Paradise", kana: "アイドントワナダイインザパラダイス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "I feel you", kana: "アイフィールユー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "KUNOICHI", kana: "クノイチ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "LOSTTIME", kana: "ロストタイム", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Love is Action!（セルフカバー）", kana: "ラブイズアクションセルフ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "MASAMUNE", kana: "マサムネ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Melodic Surfers", kana: "メロディックサーファーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Ms.Thunderbolt", kana: "ミスサンダーボルト", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Mt. Wakakusa Starmine", kana: "マウントワカクサスターマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ORIGAMI", kana: "オリガミ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Paradise of Birds", kana: "パラダイスオブバーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "PHOENIX", kana: "フェニックス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "POKER-FACE", kana: "ポーカーフェイス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ROCKET", kana: "ロケット", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Sign", kana: "サイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "SPEECH", kana: "スピーチ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "The WORLD is Mine", kana: "ザワールドイズマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Wake Up H×ERO!", kana: "ウェイクアップエグゼロス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Xross Road", kana: "クロスロード", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ʘcean -WORLD Edition-", kana: "オーシャンワールドエディション", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "あゝ", kana: "アア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "アタシインソムニア", kana: "アタシインソムニア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "エアギターガール", kana: "エアギターガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "エレベーターガール", kana: "エレベーターガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "こどものじかん", kana: "コドモノジカン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ザ・ワールド・イズ・マイン", kana: "ザワールドイズマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "セツナヒコウキ", kana: "セツナヒコウキ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ダーウィンに捧ぐ", kana: "ダーウィンニササグ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "タイムカプセルに青空を", kana: "タイムカプセルニアオゾラヲ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ナイトサイクリング", kana: "ナイトサイクリング", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ナミタチヌ", kana: "ナミタチヌ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ハイスコアガール", kana: "ハイスコアガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ヒカリアレ", kana: "ヒカリアレ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "むー", kana: "ムー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ヨロコビノウタ", kana: "ヨロコビノウタ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ラブレター。", kana: "ラブレター", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "リフレインはもう鳴らない", kana: "リフレインハモウナラナイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ロザリオをはずして", kana: "ロザリオヲハズシテ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "逢いたい逢えない", kana: "アイタイアエナイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "或るK大生の死", kana: "アルケイダイセイノシ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "火花", kana: "ヒバナ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "花一匁", kana: "ハナイチモンメ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "我が家はルーヴル", kana: "ワガヤハルーヴル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "銀世界", kana: "ギンセカイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君のためのMusic", kana: "キミノタメノミュージック", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君は僕のRainbow", kana: "キミハボクノレインボー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君をアンインストールできたなら", kana: "キミヲアンインストールデキタナラ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "月光サンタクロース", kana: "ゲッコウサンタクロース", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "月光蝶", kana: "ゲッコウチョウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "吾輩は猫である", kana: "ワガハイハネコデアル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "国士無双役満少女", kana: "コクシムソウヤクマンショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "斜陽", kana: "シャヨウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "邪教・拝金教", kana: "ジャキョウハイキンキョウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "若草山スターマイン", kana: "ワカクサヤマスターマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "初恋カプチーノ", kana: "ハツコイカプチーノ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "神戸在住", kana: "コウベザイジュウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "人工衛星", kana: "ジンコウエイセイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "数學少女", kana: "スウガクショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "数學少女Z", kana: "スウガクショウジョゼット", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "世界は愛で満ちている", kana: "セカイハアイデミチテイル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "世界を回せ", kana: "セカイヲマワセ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星の王子さま-Fin-", kana: "ホシノオウジサマフィン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星の王子さま-Ouverture-", kana: "ホシノオウジサマウーヴァチュア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星屑ライダーズ", kana: "ホシクズライダーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "墜落 / 上昇", kana: "ツイラクジョウショウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "庭球行進曲", kana: "テイキュウコウシンキョク", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "東名高速道路清水JCTを時速二〇〇キロメートル超で駆け抜けるのさ", kana: "トウメイコウソクドウロシミズジャンクション", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "白線渡り", kana: "ハクセンワタリ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "文學少女", kana: "ブンガクショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "魔王", kana: "マオウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "模範囚", kana: "モハンシュウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "檸檬", kana: "レモン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
*/
/*
    //===========================
    //machico
    //===========================
    { name: "1ミリ Symphony", kana: "イチミリシンフォニー", taibanFlag: true },
    { name: "beautiful days!", kana: "ビューティフルデイズ", taibanFlag: true },
    { name: "BRAND NEW WORLD ～明日へのグラデーション～", kana: "ブランドニューワールドアシタヘノグラデーション", taibanFlag: true },
    { name: "Break the ice", kana: "ブレイクザアイス", taibanFlag: true },
    { name: "Cheers!デリシャスパーティ♡プリキュア", kana: "チアーズデリシャスパーティプリキュア", taibanFlag: true, subInfo: "デリシャスパーティ♡プリキュア" },
    { name: "CLAP!〜勇気を鳴らせ〜", kana: "クラップユウキヲナラセ", taibanFlag: true, subInfo: "トロピカル〜ジュ!プリキュア" },
    { name: "Do You Believe in Magic?", kana: "ドゥユービリーブインマジック", taibanFlag: true },
    { name: "ENISHI", kana: "エニシ", taibanFlag: true },
    { name: "Everlasting Glory", kana: "エバーラスティンググローリー", taibanFlag: true },
    { name: "fantastic dreamer", kana: "ファンタスティックドリーマー", taibanFlag: true },
    { name: "Girls Be Ambitious!!", kana: "ガールズビーアンビシャス", taibanFlag: true },
    { name: "Growing Up", kana: "グローイングアップ", taibanFlag: true },
    { name: "Happy Gathering", kana: "ハッピーギャザリング", taibanFlag: true },
    { name: "Happy Magic", kana: "ハッピーマジック", taibanFlag: true },
    { name: "IGNITION", kana: "イグニッション", taibanFlag: true, subInfo: "岬あやね（キラキラ☆プリキュアアラモード）" },
    { name: "key of the future", kana: "キーオブザフューチャー", taibanFlag: true },
    { name: "LOVE FOR ALL", kana: "ラブフォーオール", taibanFlag: true, subInfo: "ヒーリングっど♡プリキュア" },
    { name: "Lunar eclipse", kana: "ルナエクリプス", taibanFlag: true },
    { name: "Magical Happy Show!", kana: "マジカルハッピーショー", taibanFlag: true },
    { name: "Million Smile", kana: "ミリオンスマイル", taibanFlag: true },
    { name: "OVER HEAT", kana: "オーバーヒート", taibanFlag: true },
    { name: "POPPING NOW", kana: "ポッピングナウ", taibanFlag: true },
    { name: "Shall we…?", kana: "シャルウィー", taibanFlag: true },
    { name: "Soul Believer", kana: "ソウルビリーバー", taibanFlag: true, subInfo: "岬あやね（キラキラ☆プリキュアアラモード）" },
    { name: "STAND UP!", kana: "スタンドアップ", taibanFlag: true },
    { name: "STAY FREE", kana: "ステイフリー", taibanFlag: true },
    { name: "The Magical Conductor.", kana: "ザマジカルコンダクター", taibanFlag: true },
    { name: "thread a needle", kana: "スレッドアニードル", taibanFlag: true },
    { name: "TOMORROW", kana: "トゥモロー", taibanFlag: true },
    { name: "Viva! Spark!トロピカル〜ジュ!プリキュア", kana: "ビバスパークトロピカルージュプリキュア", taibanFlag: true, subInfo: "トロピカル〜ジュ!プリキュア" },
    { name: "Zeal", kana: "ジール", taibanFlag: true },
    { name: "カーテン", kana: "カーテン", taibanFlag: true },
    { name: "きっとショコラ", kana: "キットショコラ", taibanFlag: true },
    { name: "ギミー・ラブ", kana: "ギミーラブ", taibanFlag: true },
    { name: "キミコンパス", kana: "キミコンパス", taibanFlag: true },
    { name: "ぐるぐるコンティニュー", kana: "グルグルコンティニュー", taibanFlag: true },
    { name: "ココロメロディー", kana: "ココロメロディー", taibanFlag: true },
    { name: "コレカラ", kana: "コレカラ", taibanFlag: true },
    { name: "シェアして！プリキュア Machico Ver.", kana: "シェアシテプリキュアマチコバージョン" },
    { name: "ピンクトルマリン", kana: "ピンクトルマリン" },
    { name: "マケズギライなThank you", kana: "マケズギライナサンキュー" },
    { name: "またあした", kana: "マタアシタ" },
    { name: "ミライロケット", kana: "ミライロケット" },
    { name: "ミラクルっと♡Link Ring!", kana: "ミラクルットリンクリング", subInfo: "ヒーリングっど♡プリキュア" },
    { name: "やくそく 〜Original Remix Version〜", kana: "ヤクソクオリジナルリミックスバージョン", subInfo: "映画ヒーリングっど♡プリキュア ゆめのまちでキュン!っとGoGo!大変身!!" },
    { name: "ラブ★スト", kana: "ラブスト" },
    { name: "ワイルドカード", kana: "ワイルドカード" },
    { name: "ワタシイロ", kana: "ワタシイロ" },
    { name: "一緒に帰ろう", kana: "イッショニカエロウ" },
    { name: "永久味方宣言", kana: "エイキュウミカタセンゲン" },
    { name: "花音", kana: "カノン" },
    { name: "禁断の運命", kana: "キンダンノウンメイ" },
    { name: "向こう見ずFORWARD", kana: "ムコウミズフォワード" },
    { name: "好き嫌いニュービート", kana: "スキキライニュービート" },
    { name: "紅花火", kana: "ベニハナビ" },
    { name: "若葉のころ", kana: "ワカバノコロ", subInfo: "映画プリキュアミラクルリープ みんなとの不思議な1日" },
    { name: "星の旅は夢うつつ", kana: "ホシノタビハユメウツツ" },
    { name: "星屑プリンス", kana: "ホシクズプリンス" },
    { name: "青春オーバードライブ", kana: "セイシュンオーバードライブ" },
    { name: "大好きのSnowball", kana: "ダイスキノスノーボール", subInfo: "映画トロピカル〜ジュ!プリキュア 雪のプリンセスと奇跡の指輪!" },
    { name: "日曜日のともだち", kana: "ニチヨウビノトモダチ" },
    { name: "摩天楼グッバイ", kana: "マテンロウグッバイ" },
    { name: "勇気のつばさ", kana: "ユウキノツバサ" },
    { name: "有頂天", kana: "ウチョウテン" },
    */
    

];

// 五十音順にソートする処理もこちらにまとめておきます
songList.sort((a, b) => a.kana.localeCompare(b.kana, 'ja'));
