// =========================================
// 曲目リストデータ（songList.js）
// =========================================

const songList = [
    { name: "I wish", kana: "アイウィッシュ" },
    { name: "identity my ultimatum", kana: "アイデンティティマイアルティメイタム", subInfo: "Sho from MY FIRST STORY feat.駒形友梨/ウエノルカ(眩暈SIREN)" },
    { name: "アクアリウム", kana: "アクアリウム" },
    { name: "a Day~and the light comes~", kana: "アデイアンドザライトカムズ" },
    { name: "our story", kana: "アワーストーリー" },
    { name: "Yellow Love", kana: "イエローラブ" },
    { name: "It's HEAVEN", kana: "イッツヘブン" },
    { name: "invincible self", kana: "インヴィンシブルセルフ" },
    { name: "insomnia", kana: "インソムニア" },
    { name: "Welcome!!", kana: "ウェルカム", subInfo: "765 MILLION ALLSTARS" },
    { name: "empty", kana: "エンプティ" },
    { name: "August 31", kana: "オーガストサーティファースト" },
    { name: "オービタル", kana: "オービタル" },
    { name: "All for one Forever", kana: "オールフォーワンフォーエバー", subInfo: "映画プリキュアオールスターズF" },
    { name: "おそろい", kana: "オソロイ" },
    { name: "On My Way", kana: "オンマイウェイ" },
    { name: "カラフルVacation", kana: "カラフルバケーション", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "創だらけの詩", kana: "キズダラケノウタ" },
    { name: "キミと恋の予感", kana: "キミトコイノヨカン" },
    { name: "君の心に触れる歌", kana: "キミノココロニフレルウタ" },
    { name: "今日は", kana: "キョウハ" },
    { name: "キラキラ⭐︎スイート⭐︎マドモアゼル", kana: "キラキラスイートマドモアゼル", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "グッドサイン", kana: "グッドサイン", subInfo: "765 MILLION ALLSTARS" },
    { name: "Good Night", kana: "グッドナイト" },
    { name: "Glow Map", kana: "グロウマップ", subInfo: "765 MILLION ALLSTARS" },
    { name: "クロックワイズ", kana: "クロックワイズ" },
    { name: "Crossing!", kana: "クロッシング", subInfo: "765 MILLION ALLSTARS" },
    { name: "クロワッサン", kana: "クロワッサン" },
    { name: "孤悲", kana: "コイ" },
    { name: "going forward", kana: "ゴーイングフォーワード" },
    { name: "call me today", kana: "コールミートゥデイ" },
    { name: "コンパス", kana: "コンパス" },
    { name: "Thank You!", kana: "サンキュー", subInfo: "765 MILLION ALLSTARS" },
    { name: "SHINE!! キラキラ⭐︎プリキュアアラモード", kana: "シャインキラキラプリキュアアラモード", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "Champagne Gold", kana: "シャンパンゴールド", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "シングデイズ", kana: "シングデイズ" },
    { name: "真珠星", kana: "シンジュボシ" },
    { name: "starting in the haze", kana: "スターティングインザヘイズ" },
    { name: "SPARKERS", kana: "スパーカーズ", subInfo: "高山紗代子" },
    { name: "7Days A Week!!", kana: "セブンデイズアウィーク", subInfo: "765 MILLION ALLSTARS" },
    { name: "ソノヒ", kana: "ソノヒ" },
    { name: "蝶々むすび", kana: "チョウチョムスビ", subInfo: "765 MILLION ALLSTARS" },
    { name: "2 world", kana: "ツーワールド" },
    { name: "Talk 2 Night", kana: "トークトゥナイト" },
    { name: "時の葉", kana: "トキノハ" },
    { name: "トマレのススメ", kana: "トマレノススメ" },
    { name: "Dreaming!", kana: "ドリーミング", subInfo: "765 MILLION ALLSTARS" },
    { name: "Dreaming Night", kana: "ドリーミングナイト" },
    { name: "Night Walk", kana: "ナイトウォーク" },
    { name: "night sea", kana: "ナイトシー" },
    { name: "Neon Sign", kana: "ネオンサイン" },
    { name: "NExt Wave!!", kana: "ネクストウェーブ", subInfo: "PA大海物語 With アグネス・ラム" },
    { name: "Harmony 4 You", kana: "ハーモニーフォーユー", subInfo: "765 MILLION ALLSTARS" },
    { name: "ばいばい", kana: "バイバイ" },
    { name: "はじめからきっと", kana: "ハジメカラキット" },
    { name: "happy weekend", kana: "ハッピーウィークエンド" },
    { name: "Here I Am", kana: "ヒアアイアム" },
    { name: "ビターフラッペ", kana: "ビターフラッペ" },
    { name: "First Step", kana: "ファーストステップ" },
    { name: "FLY!", kana: "フライ" },
    { name: "Flyers!!!", kana: "フライヤーズ", subInfo: "765 MILLION ALLSTARS" },
    { name: "Brand New Theater!", kana: "ブランニューシアター", subInfo: "765 MILLION ALLSTARS" },
    { name: "メイズ", kana: "メイズ" },
    { name: "優しい雨", kana: "ヤサシイアメ" },
    { name: "勇気が君を待ってる", kana: "ユウキガキミヲマッテル", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "UNION!!", kana: "ユニオン", subInfo: "765 MILLION ALLSTARS" },
    { name: "夢にかけるRainbow", kana: "ユメニカケルレインボー", subInfo: "765 MILLION ALLSTARS" },
    { name: "Rat A Tat!!!", kana: "ラタタ", subInfo: "765 MILLION ALLSTARS" },
    { name: "Love is Action!", kana: "ラブイズアクション" },
    { name: "ララルハレルヤ", kana: "ララルハレルヤ" },
    { name: "リコリス", kana: "リコリス", subInfo: "東堂凛（OVER RUN!!）" },
    { name: "Lu La La⭐︎Lumière", kana: "ルララルミエール", subInfo: "キラキラ⭐︎プリキュアアラモード" },
    { name: "Lonely Blue が終わる頃には", kana: "ロンリーブルーガオワルコロニハ" },
    { name: "Many Many Musik", kana: "メニメニムジーク" },
    { name: "トレビアンサンブル!!", kana: "トレビアンサンブル", subInfo: "映画キラキラ☆プリキュアアラモード パリッと!想い出のミルフィーユ!" },
    { name: "We are the future！", kana: "ウィーアーザフューチャー" },
    /*
    //===========================    
    //BURNOUT SYNDROMES
    //===========================
    { name: "100万回のアイ・ラヴ・ユー", kana: "ヒャクマカイノアイラブユー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "2020年渋谷の旅", kana: "ニセンニジュウネンシブヤノタビ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Amateras", kana: "アマテラス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BABEL", kana: "バベル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BLIZZARD", kana: "ブリザード", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Bottle Ship Boys", kana: "ボトルシップボーイズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "BREAK DANCER", kana: "ブレイクダンサー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Dragonfly", kana: "ドラゴンフライ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Dream On!!", kana: "ドリームオン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "FLY HIGH!!", kana: "フライハイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "FORÇA", kana: "フォルサ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Good Morning [New] World!", kana: "グッドモーニングニューワールド", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Good Morning World!", kana: "グッドモーニングワールド", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Hikousen", kana: "ヒコウセン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "i am a HERO", kana: "アイアムアヒーロー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "I Don’t Wanna Die in the Paradise", kana: "アイドントワナダイインザパラダイス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "I feel you", kana: "アイフィールユー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "KUNOICHI", kana: "クノイチ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "LOSTTIME", kana: "ロストタイム", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Love is Action!（セルフカバー）", kana: "ラブイズアクションセルフ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "MASAMUNE", kana: "マサムネ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Melodic Surfers", kana: "メロディックサーファーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Ms.Thunderbolt", kana: "ミスサンダーボルト", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Mt. Wakakusa Starmine", kana: "マウントワカクサスターマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ORIGAMI", kana: "オリガミ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Paradise of Birds", kana: "パラダイスオブバーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "PHOENIX", kana: "フェニックス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "POKER-FACE", kana: "ポーカーフェイス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ROCKET", kana: "ロケット", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Sign", kana: "サイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "SPEECH", kana: "スピーチ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "The WORLD is Mine", kana: "ザワールドイズマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Wake Up H×ERO!", kana: "ウェイクアップエグゼロス", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "Xross Road", kana: "クロスロード", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ʘcean -WORLD Edition-", kana: "オーシャンワールドエディション", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "あゝ", kana: "アア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "アタシインソムニア", kana: "アタシインソムニア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "エアギターガール", kana: "エアギターガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "エレベーターガール", kana: "エレベーターガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "こどものじかん", kana: "コドモノジカン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "セツナヒコウキ", kana: "セツナヒコウキ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ダーウィンに捧ぐ", kana: "ダーウィンニササグ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "タイムカプセルに青空を", kana: "タイムカプセルニアオゾラヲ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ナイトサイクリング", kana: "ナイトサイクリング", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ナミタチヌ", kana: "ナミタチヌ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ハイスコアガール", kana: "ハイスコアガール", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ヒカリアレ", kana: "ヒカリアレ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "むー", kana: "ムー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ヨロコビノウタ", kana: "ヨロコビノウタ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ラブレター。", kana: "ラブレター", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "リフレインはもう鳴らない", kana: "リフレインハモウナラナイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "ロザリオをはずして", kana: "ロザリオヲハズシテ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "逢いたい逢えない", kana: "アイタイアエナイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "或るK大生の死", kana: "アルケイダイセイノシ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "火花", kana: "ヒバナ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "花一匁", kana: "ハナイチモンメ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "我が家はルーヴル", kana: "ワガヤハルーヴル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "銀世界", kana: "ギンセカイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君のためのMusic", kana: "キミノタメノミュージック", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君は僕のRainbow", kana: "キミハボクノレインボー", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "君をアンインストールできたなら", kana: "キミヲアンインストールデキタナラ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "月光サンタクロース", kana: "ゲッコウサンタクロース", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "月光蝶", kana: "ゲッコウチョウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "吾輩は猫である", kana: "ワガハイハネコデアル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "国士無双役満少女", kana: "コクシムソウヤクマンショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "斜陽", kana: "シャヨウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "邪教・拝金教", kana: "ジャキョウハイキンキョウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "若草山スターマイン", kana: "ワカクサヤマスターマイン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "初恋カプチーノ", kana: "ハツコイカプチーノ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "神戸在住", kana: "コウベザイジュウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "人工衛星", kana: "ジンコウエイセイ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "数學少女", kana: "スウガクショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "数學少女Z", kana: "スウガクショウジョゼット", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "世界は愛で満ちている", kana: "セカイハアイデミチテイル", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "世界を回せ", kana: "セカイヲマワセ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星の王子さま-Fin-", kana: "ホシノオウジサマフィン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星の王子さま-Ouverture-", kana: "ホシノオウジサマウーヴァチュア", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "星屑ライダーズ", kana: "ホシクズライダーズ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "墜落 / 上昇", kana: "ツイラクジョウショウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "庭球行進曲", kana: "テイキュウコウシンキョク", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "東名高速道路清水JCTを時速二〇〇キロメートル超で駆け抜けるのさ", kana: "トウメイコウソクドウロシミズジャンクション", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "白線渡り", kana: "ハクセンワタリ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "文學少女", kana: "ブンガクショウジョ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "魔王", kana: "マオウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "模範囚", kana: "モハンシュウ", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
    { name: "檸檬", kana: "レモン", taibanFlag: true, subInfo: "BURNOUT SYNDROMES" },
*/

    //===========================
    //machico
    //===========================
    { name: "1ミリ Symphony", kana: "イチミリシンフォニー", taibanFlag: true },
    { name: "beautiful days!", kana: "ビューティフルデイズ", taibanFlag: true },
    { name: "BRAND NEW WORLD ～明日へのグラデーション～", kana: "ブランドニューワールドアシタヘノグラデーション", taibanFlag: true },
    { name: "Break the ice", kana: "ブレイクザアイス", taibanFlag: true },
    { name: "Cheers!デリシャスパーティ♡プリキュア", kana: "チアーズデリシャスパーティプリキュア", taibanFlag: true, subInfo: "デリシャスパーティ♡プリキュア" },
    { name: "CLAP!〜勇気を鳴らせ〜", kana: "クラップユウキヲナラセ", taibanFlag: true, subInfo: "トロピカル〜ジュ!プリキュア" },
    { name: "Do You Believe in Magic?", kana: "ドゥユービリーブインマジック", taibanFlag: true },
    { name: "ENISHI", kana: "エニシ", taibanFlag: true },
    { name: "Everlasting Glory", kana: "エバーラスティンググローリー", taibanFlag: true },
    { name: "fantastic dreamer", kana: "ファンタスティックドリーマー", taibanFlag: true },
    { name: "Girls Be Ambitious!!", kana: "ガールズビーアンビシャス", taibanFlag: true },
    { name: "Growing Up", kana: "グローイングアップ", taibanFlag: true },
    { name: "Happy Gathering", kana: "ハッピーギャザリング", taibanFlag: true },
    { name: "Happy Magic", kana: "ハッピーマジック", taibanFlag: true },
    { name: "IGNITION", kana: "イグニッション", taibanFlag: true, subInfo: "岬あやね（キラキラ☆プリキュアアラモード）" },
    { name: "key of the future", kana: "キーオブザフューチャー", taibanFlag: true },
    { name: "LOVE FOR ALL", kana: "ラブフォーオール", taibanFlag: true, subInfo: "ヒーリングっど♡プリキュア" },
    { name: "Lunar eclipse", kana: "ルナエクリプス", taibanFlag: true },
    { name: "Magical Happy Show!", kana: "マジカルハッピーショー", taibanFlag: true },
    { name: "Million Smile", kana: "ミリオンスマイル", taibanFlag: true },
    { name: "OVER HEAT", kana: "オーバーヒート", taibanFlag: true },
    { name: "POPPING NOW", kana: "ポッピングナウ", taibanFlag: true },
    { name: "Shall we…?", kana: "シャルウィー", taibanFlag: true },
    { name: "Soul Believer", kana: "ソウルビリーバー", taibanFlag: true, subInfo: "岬あやね（キラキラ☆プリキュアアラモード）" },
    { name: "STAND UP!", kana: "スタンドアップ", taibanFlag: true },
    { name: "STAY FREE", kana: "ステイフリー", taibanFlag: true },
    { name: "The Magical Conductor.", kana: "ザマジカルコンダクター", taibanFlag: true },
    { name: "thread a needle", kana: "スレッドアニードル", taibanFlag: true },
    { name: "TOMORROW", kana: "トゥモロー", taibanFlag: true },
    { name: "Viva! Spark!トロピカル〜ジュ!プリキュア", kana: "ビバスパークトロピカルージュプリキュア", taibanFlag: true, subInfo: "トロピカル〜ジュ!プリキュア" },
    { name: "Zeal", kana: "ジール", taibanFlag: true },
    { name: "カーテン", kana: "カーテン", taibanFlag: true },
    { name: "きっとショコラ", kana: "キットショコラ", taibanFlag: true },
    { name: "ギミー・ラブ", kana: "ギミーラブ", taibanFlag: true },
    { name: "キミコンパス", kana: "キミコンパス", taibanFlag: true },
    { name: "ぐるぐるコンティニュー", kana: "グルグルコンティニュー", taibanFlag: true },
    { name: "ココロメロディー", kana: "ココロメロディー", taibanFlag: true },
    { name: "コレカラ", kana: "コレカラ", taibanFlag: true },
    { name: "シェアして！プリキュア", kana: "シェアシテプリキュア", taibanFlag: true },
    { name: "ピンクトルマリン", kana: "ピンクトルマリン", taibanFlag: true },
    { name: "マケズギライなThank you", kana: "マケズギライナサンキュー", taibanFlag: true },
    { name: "またあした", kana: "マタアシタ", taibanFlag: true },
    { name: "ミライロケット", kana: "ミライロケット", taibanFlag: true },
    { name: "ミラクルっと♡Link Ring!", kana: "ミラクルットリンクリング", taibanFlag: true, subInfo: "ヒーリングっど♡プリキュア" },
    { name: "やくそく 〜Original Remix Version〜", kana: "ヤクソクオリジナルリミックスバージョン", taibanFlag: true, subInfo: "映画ヒーリングっど♡プリキュア ゆめのまちでキュン!っとGoGo!大変身!!" },
    { name: "ラブ★スト", kana: "ラブスト", taibanFlag: true },
    { name: "ワイルドカード", kana: "ワイルドカード", taibanFlag: true },
    { name: "ワタシイロ", kana: "ワタシイロ", taibanFlag: true },
    { name: "一緒に帰ろう", kana: "イッショニカエロウ", taibanFlag: true },
    { name: "永久味方宣言", kana: "エイキュウミカタセンゲン", taibanFlag: true },
    { name: "花音", kana: "カノン", taibanFlag: true },
    { name: "禁断の運命", kana: "キンダンノウンメイ", taibanFlag: true },
    { name: "向こう見ずFORWARD", kana: "ムコウミズフォワード", taibanFlag: true },
    { name: "好き嫌いニュービート", kana: "スキキライニュービート", taibanFlag: true },
    { name: "紅花火", kana: "ベニハナビ", taibanFlag: true },
    { name: "若葉のころ", kana: "ワカバノコロ", taibanFlag: true, subInfo: "映画プリキュアミラクルリープ みんなとの不思議な1日" },
    { name: "星の旅は夢うつつ", kana: "ホシノタビハユメウツツ", taibanFlag: true },
    { name: "星屑プリンス", kana: "ホシクズプリンス", taibanFlag: true },
    { name: "青春オーバードライブ", kana: "セイシュンオーバードライブ", taibanFlag: true },
    { name: "大好きのSnowball", kana: "ダイスキノスノーボール", taibanFlag: true, subInfo: "映画トロピカル〜ジュ!プリキュア 雪のプリンセスと奇跡の指輪!" },
    { name: "日曜日のともだち", kana: "ニチヨウビノトモダチ", taibanFlag: true },
    { name: "摩天楼グッバイ", kana: "マテンロウグッバイ", taibanFlag: true },
    { name: "勇気のつばさ", kana: "ユウキノツバサ", taibanFlag: true },
    { name: "有頂天", kana: "ウチョウテン", taibanFlag: true },



    //===========================
    //中島愛
    //===========================
    { name: "All Green", kana: "オール グリーン", taibanFlag: true },
    { name: "Ame (Rain) ", kana: "アメ レイン", taibanFlag: true },
    { name: "Another Letter", kana: "アナザー レター", taibanFlag: true, subInfo: "枝葉柚希（君のいる町）" },
    { name: "Be MYSELF", kana: "ビー マイセルフ", taibanFlag: true },
    { name: "Bitter Sweet Harmony", kana: "ビター スウィート ハーモニー", taibanFlag: true },
    { name: "CALL ME", kana: "コール ミー", taibanFlag: true },
    { name: "Carry Out!", kana: "キャリー アウト", taibanFlag: true },
    { name: "COSMOS", kana: "コスモス", taibanFlag: true, subInfo: "Citoron（バスカッシュ！）" },
    { name: "epilogue -instrumental-", kana: "エピローグ インストゥルメンタル", taibanFlag: true },
    { name: "equal", kana: "イコール", taibanFlag: true },
    { name: "Flower in Green", kana: "フラワー イン グリーン", taibanFlag: true },
    { name: "FLY", kana: "フライ", taibanFlag: true },
    { name: "GREEN DIARY", kana: "グリーン ダイアリー", taibanFlag: true },
    { name: "Hello！", kana: "ハロー", taibanFlag: true },
    { name: "I AM", kana: "アイ アム", taibanFlag: true },
    { name: "Jewel", kana: "ジュエル", taibanFlag: true },
    { name: "Kimono Beat<松田聖子>　　", kana: "キモノ ビート マツダセイコ", taibanFlag: true },
    { name: "Life’s The Party Time!!", kana: "ライフズ ザ パーティー タイム", taibanFlag: true },
    { name: "Love! For Your Love!", kana: "ラブ フォー ユア ラブ", taibanFlag: true },
    { name: "Mamegu A Go! Go!", kana: "マメグ ア ゴー ゴー", taibanFlag: true },
    { name: "Megu2 Magic", kana: "メグメグ マジック", taibanFlag: true },
    { name: "Odyssey", kana: "オデッセイ", taibanFlag: true },
    { name: "Over & Over", kana: "オーバー アンド オーバー", taibanFlag: true },
    { name: "PEACE&LUCK", kana: "ピース アンド ラック", taibanFlag: true, subInfo: "レーネ（武装神姫）" },
    { name: "Pharaoh★Love", kana: "ファラオ ラブ", taibanFlag: true, subInfo: "ニキ・サマーフィールド（NeverDead）" },
    { name: "prologue -instrumental-", kana: "プロローグ インストゥルメンタル", taibanFlag: true },
    { name: "Raspberry Kiss", kana: "ラズベリー キス", taibanFlag: true },
    { name: "Shining on", kana: "シャイニング オン", taibanFlag: true },
    { name: "SINCERELY", kana: "シンシアリー", taibanFlag: true, subInfo: "春日部耀（問題児たちが異世界から来るそうですよ？）" },
    { name: "Sunshine Girl", kana: "サンシャイン ガール", taibanFlag: true },
    { name: "Transfer", kana: "トランスファー", taibanFlag: true },
    { name: "TRY UNITE！", kana: "トライ ユナイト", taibanFlag: true },
    { name: "Wake Up!", kana: "ウェイク アップ", taibanFlag: true },
    { name: "white heart rhythm", kana: "ホワイト ハート リズム", taibanFlag: true },
    { name: "Wish", kana: "ウィッシュ", taibanFlag: true },
    { name: "アイモ", kana: "アイモ", taibanFlag: true, subInfo: "ランカ･リー" },
    { name: "あの日の海", kana: "アノヒノウミ", taibanFlag: true },
    { name: "ありがとう", kana: "アリガトウ", taibanFlag: true },
    { name: "いにしえの歌（キラキラVer.）", kana: "イニシエノウタ キラキラバージョン", taibanFlag: true, subInfo: "メロエッタ（劇場版「ポケットモンスター ベストウイッシュ メロエッタのキラキラリサイタル」）" },
    { name: "ウソツキザクラ", kana: "ウソツキザクラ", taibanFlag: true },
    { name: "くちびるの奥の宇宙", kana: "クチビルノオクノウチュウ", taibanFlag: true },
    { name: "サタデー・ナイト・クエスチョン", kana: "サタデー ナイト クエスチョン", taibanFlag: true },
    { name: "サブマリーン", kana: "サブマリーン", taibanFlag: true },
    { name: "ジェリーフィッシュの告白", kana: "ジェリーフィッシュノコクハク", taibanFlag: true },
    { name: "ずっと一緒", kana: "ズットイッショ", taibanFlag: true, subInfo: "保志まなみ（たまゆら～hitotose～）" },
    { name: "セイシェルの夕陽/原曲：松田聖子", kana: "セイシェルノユウヒ ゲンキョク マツダセイコ", taibanFlag: true },
    { name: "そんなこと裏のまた裏話でしょ？", kana: "ソンナコトウラノマタウラバナシデショ", taibanFlag: true },
    { name: "つながるまで", kana: "ツナガルマデ", taibanFlag: true },
    { name: "とうめいにんげん", kana: "トウメイニンゲン", taibanFlag: true },
    { name: "ドデカ･ラブ", kana: "ドデカラブ", taibanFlag: true, subInfo: "キュアラブリー（ハピネスチャージプリキュア！）" },
    { name: "ドライブ", kana: "ドライブ", taibanFlag: true },
    { name: "ねこ日記", kana: "ネコニッキ", taibanFlag: true },
    { name: "ノスタルジア", kana: "ノスタルジア", taibanFlag: true },
    { name: "ハイブリッド　スターチス", kana: "ハイブリッド スターチス", taibanFlag: true },
    { name: "ホシキラ", kana: "ホシキラ", taibanFlag: true, subInfo: "ランカ･リー" },
    { name: "マーブル", kana: "マーブル", taibanFlag: true },
    { name: "メロディ", kana: "メロディ", taibanFlag: true },
    { name: "メロンソーダ・フロート", kana: "メロンソーダ フロート", taibanFlag: true },
    { name: "ゆびさきの雨", kana: "ユビサキノアメ", taibanFlag: true },
    { name: "ライオン", kana: "ライオン", taibanFlag: true, subInfo: "May'n,中島　愛" },
    { name: "ライオン -ランカver.-", kana: "ライオン ランカバージョン", taibanFlag: true, subInfo: "ランカ･リー" },
    { name: "リルロマンティック feat. GUMI", kana: "リルロマンティック フィーチャリング グミ", taibanFlag: true },
    { name: "わたしにできること", kana: "ワタシニデキルコト", taibanFlag: true },
    { name: "ワタシノセカイ", kana: "ワタシノセカイ", taibanFlag: true },
    { name: "愛・おぼえていますか", kana: "アイ オボエテイマスカ", taibanFlag: true },
    { name: "愛の重力", kana: "アイノジュウリョク", taibanFlag: true },
    { name: "愛はめぐる", kana: "アイハメグル", taibanFlag: true },
    { name: "愛を灯して", kana: "アイヲトモシテ", taibanFlag: true },
    { name: "宇宙的DON-DOKO-DON", kana: "ウチュウテキドンドコドン", taibanFlag: true },
    { name: "雨にキッスの花束を<今井美樹>　", kana: "アメニキッスノハナタバヲ イマイミキ", taibanFlag: true },
    { name: "遠く君へ", kana: "トオクキミヘ", taibanFlag: true, subInfo: "アンヌ（異国迷路のクロワーゼ The Animation）" },
    { name: "夏の記憶", kana: "ナツノキオク", taibanFlag: true },
    { name: "夏鳥", kana: "ナツドリ", taibanFlag: true },
    { name: "金色～君を好きになってよかった", kana: "コンジキ キミヲスキニナッテヨカッタ", taibanFlag: true },
    { name: "空色ラブレター", kana: "ソライロラブレター", taibanFlag: true },
    { name: "好キッス! KISS!!", kana: "スキッス キッス", taibanFlag: true },
    { name: "最高の瞬間", kana: "サイコウノシュンカン", taibanFlag: true },
    { name: "残像のアヴァロン", kana: "ザンゾウノアヴァロン", taibanFlag: true },
    { name: "思い出に変わるまで", kana: "オモイデニカワルマデ", taibanFlag: true },
    { name: "私の彼はパイロット", kana: "ワタシノカレハパイロット", taibanFlag: true },
    { name: "時に愛は<松本伊代>　　", kana: "トキニアイハ マツモトイヨ", taibanFlag: true },
    { name: "真夜中のドア<松原みき>　　", kana: "マヨナカノドア マツバラミキ", taibanFlag: true },
    { name: "神様のいたずら", kana: "カミサマノイタズラ", taibanFlag: true },
    { name: "水槽", kana: "スイソウ", taibanFlag: true },
    { name: "星間飛行", kana: "セイカンヒコウ", taibanFlag: true, subInfo: "ランカ･リー" },
    { name: "青いスタスィオン<河合その子>　", kana: "アオイスタスィオン カワイソノコ", taibanFlag: true },
    { name: "素顔でフォーリンラブ", kana: "スガオデフォーリンラブ", taibanFlag: true, subInfo: "沙倉 楓（けんぷファー）" },
    { name: "窓際のジェラシー", kana: "マドギワノジェラシー", taibanFlag: true },
    { name: "知らない気持ち", kana: "シラナイキモチ", taibanFlag: true },
    { name: "天使になりたい", kana: "テンシニナリタイ", taibanFlag: true },
    { name: "天使の憂鬱", kana: "テンシノユウウツ", taibanFlag: true },
    { name: "透明なオレンジ<安田成美>　", kana: "トウメイナオレンジ ヤスダナルミ", taibanFlag: true },
    { name: "髪飾りの天使", kana: "カミカザリノテンシ", taibanFlag: true },
    { name: "悲しみと共に", kana: "カナシミトトモニ", taibanFlag: true },
    { name: "風色のフィルム", kana: "カゼイロノフィルム", taibanFlag: true },
    { name: "放課後オーバーフロウ", kana: "ホウカゴオーバーフロウ", taibanFlag: true, subInfo: "ランカ･リー" },
    { name: "忘れないよ。", kana: "ワスレナイヨ", taibanFlag: true },
    { name: "未来の記憶", kana: "ミライノキオク", taibanFlag: true },
    { name: "未来の栞", kana: "ミライノシオリ", taibanFlag: true, subInfo: "藍羽ルリ（セイクリッドセブン）" },
    { name: "無言のファルセット(with Negicco)　<CoCo>　", kana: "ムゴンノファルセット ウィズ ネギッコ ココ", taibanFlag: true },
    { name: "粒マスタードのマーチ", kana: "ツブマスタードノマーチ", taibanFlag: true },
    { name: "恋", kana: "コイ", taibanFlag: true },
    { name: "恋のジングル", kana: "コイノジングル", taibanFlag: true, subInfo: "めぐちゃん from ラジオ「れでぃのたしなみ」" },
    { name: "恋のパズルを解いて", kana: "コイノパズルヲトイテ", taibanFlag: true, subInfo: "姫川エレナ（ファイ・ブレイン ～神のパズル）" },
    { name: "Kailan", kana: "カイラン", taibanFlag: true },
    { name: "ハピネスチャージプリキュア！WOW！", kana: "ハピネスチャージプリキュアワオ", taibanFlag: true, subInfo: "ハピネスチャージプリキュア！" },
    { name: "プリキュア・メモリ", kana: "プリキュアメモリ", taibanFlag: true, subInfo: "ハピネスチャージプリキュア！" },
    { name: "パーティ ハズカム", kana: "パーティハズカム", taibanFlag: true, subInfo: "ハピネスチャージプリキュア！" },
    { name: "虹色ハピネス", kana: "ニジイロハピネス", taibanFlag: true, subInfo: "キュアラブリー（ハピネスチャージプリキュア！）" },


];


// 全角清音カナから半角カナへのマッピング辞書
const halfKanaMap = {
    'ア': 'ｱ', 'イ': 'ｲ', 'ウ': 'ｳ', 'エ': 'ｴ', 'オ': 'ｵ',
    'カ': 'ｶ', 'キ': 'ｷ', 'ク': 'ｸ', 'ケ': 'ｹ', 'コ': 'ｺ',
    'サ': 'ｻ', 'シ': 'ｼ', 'ス': 'ｽ', 'セ': 'ｾ', 'ソ': 'ｿ',
    'タ': 'ﾀ', 'チ': 'ﾁ', 'ツ': 'ﾂ', 'テ': 'ﾃ', 'ト': 'ﾄ',
    'ナ': 'ﾅ', 'ニ': 'ﾆ', 'ヌ': 'ﾇ', 'ネ': 'ﾈ', 'ノ': 'ﾉ',
    'ハ': 'ﾊ', 'ヒ': 'ﾋ', 'フ': 'ﾌ', 'ヘ': 'ﾍ', 'ホ': 'ﾎ',
    'マ': 'ﾏ', 'ミ': 'ﾐ', 'ム': 'ﾑ', 'メ': 'ﾒ', 'モ': 'ﾓ',
    'ヤ': 'ﾔ', 'ユ': 'ﾕ', 'ヨ': 'ﾖ',
    'ラ': 'ﾗ', 'リ': 'ﾘ', 'ル': 'ﾙ', 'レ': 'ﾚ', 'ロ': 'ﾛ',
    'ワ': 'ﾜ', 'ヲ': 'ｦ', 'ン': 'ﾝ'
};

// 全曲データに対して firstKana を追加する処理
songList.forEach(song => {
    if (song.kana) {
        // 1. NFD正規化で濁点・半濁点を分離し、最初の1文字（清音）だけを取得
        const clearChar = song.kana.normalize('NFD').charAt(0);
        
        // 2. マップを使って半角カナに変換（マップにない場合は元の文字を維持）
        song.firstKana = halfKanaMap[clearChar] || clearChar;
    } else {
        song.firstKana = "";
    }
});

// 五十音順にソートする処理
songList.sort((a, b) => a.kana.localeCompare(b.kana, 'ja'));
